### ISSUE TITLE
PR waiting to be verified

### ISSUE THREAD

**Issue by Bam92** [freeCodeCamp/FreeCodeCampTriviaQuiz#15]
Hi!

I have submitted a `PR` 8 days ago but no comment from the maintainer or someone else. Is there someone?

**Comment by OcelotDive** [comment]
Hi bam92, 
I will be closing this issue as I'm not sure it is correct to raise an issue on a repository just because your pull request has not been accepted as soon as you would like. You must appreciate that any maintainers of repos also have jobs, families, their own learning goals they are working on, etc, as I expect you do also. However, I am extremely grateful for your contribution and I do try to look in on the repository as often as I can. I do feel your PR  is a valid one which I hope to include shortly. Again thank you for your contribution and your patience.
